[bar]
font = "JetBrainsMono NFM"
size = 32
left_modules = [
    "battery",
    "cpu"
]

background = 0xffffff00

[battery]
format = "BAT {percentage}%"
border = {
    radius = 20
}

[cpu]
format = "This line was read from config"
border = {
    radius = 20
}
