[bar]
font = "JetBrainsMono NFM"
size = 32
left_modules = [
    "battery",
    "cpu",
    "workspaces"
]
center_modules = [
    "clock",
    "systray"
]

right_modules = [
    "memory",
    "temperature"
]

background = 0xffffff00

[battery]
format = "BAT {percentage}%"
poll_interval = 1000 # amount of time to wait between polls in milisecond
border = {
    radius = 20
}

[cpu]
format = "CPU: {usage}%"
border = {
    radius = 20
}

[workspaces]
format = "{index}"
focused_color = 0xff
background = 0xffff
spacing = 5
border = {
    radius = 10,
    width = 1,
    color = 0xffffffff,
}
