// This code was autogenerated with `dbus-codegen-rust -g -d org.freedesktop.DBus -p /org/freedesktop/DBus -f org.freedesktop.DBus.Monitoring`, see https://github.com/diwic/dbus-rs
use dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait OrgFreedesktopDBusMonitoring {
    fn become_monitor(&self, arg0: Vec<&str>, arg1: u32) -> Result<(), dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target = T>> OrgFreedesktopDBusMonitoring
    for blocking::Proxy<'a, C>
{
    fn become_monitor(&self, arg0: Vec<&str>, arg1: u32) -> Result<(), dbus::Error> {
        self.method_call(
            "org.freedesktop.DBus.Monitoring",
            "BecomeMonitor",
            (arg0, arg1),
        )
    }
}
