// This code was autogenerated with `dbus-codegen-rust -g -m None -d org.kde.StatusNotifierWatcher -p /StatusNotifierWatcher -f org.kde.StatusNotifierWatcher`, see https://github.com/diwic/dbus-rs
use dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait OrgKdeStatusNotifierWatcher {
    fn get_registered_items(&self) -> Result<Vec<String>, dbus::Error>;
    fn register_status_notifier_host(&self, service: &str) -> Result<(), dbus::Error>;
    fn register_status_notifier_item(&self, service: &str) -> Result<(), dbus::Error>;
    fn is_status_notifier_host_registered(&self) -> Result<bool, dbus::Error>;
    fn protocol_version(&self) -> Result<i32, dbus::Error>;
    fn registered_status_notifier_items(&self) -> Result<Vec<String>, dbus::Error>;
}

#[derive(Debug)]
pub struct OrgKdeStatusNotifierWatcherStatusNotifierHostRegistered {}

impl arg::AppendAll for OrgKdeStatusNotifierWatcherStatusNotifierHostRegistered {
    fn append(&self, _: &mut arg::IterAppend) {}
}

impl arg::ReadAll for OrgKdeStatusNotifierWatcherStatusNotifierHostRegistered {
    fn read(_: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgKdeStatusNotifierWatcherStatusNotifierHostRegistered {})
    }
}

impl dbus::message::SignalArgs for OrgKdeStatusNotifierWatcherStatusNotifierHostRegistered {
    const NAME: &'static str = "StatusNotifierHostRegistered";
    const INTERFACE: &'static str = "org.kde.StatusNotifierWatcher";
}

#[derive(Debug)]
pub struct OrgKdeStatusNotifierWatcherStatusNotifierItemRegistered {
    pub service: String,
}

impl arg::AppendAll for OrgKdeStatusNotifierWatcherStatusNotifierItemRegistered {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.service, i);
    }
}

impl arg::ReadAll for OrgKdeStatusNotifierWatcherStatusNotifierItemRegistered {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgKdeStatusNotifierWatcherStatusNotifierItemRegistered { service: i.read()? })
    }
}

impl dbus::message::SignalArgs for OrgKdeStatusNotifierWatcherStatusNotifierItemRegistered {
    const NAME: &'static str = "StatusNotifierItemRegistered";
    const INTERFACE: &'static str = "org.kde.StatusNotifierWatcher";
}

#[derive(Debug)]
pub struct OrgKdeStatusNotifierWatcherStatusNotifierItemUnregistered {
    pub service: String,
}

impl arg::AppendAll for OrgKdeStatusNotifierWatcherStatusNotifierItemUnregistered {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.service, i);
    }
}

impl arg::ReadAll for OrgKdeStatusNotifierWatcherStatusNotifierItemUnregistered {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgKdeStatusNotifierWatcherStatusNotifierItemUnregistered { service: i.read()? })
    }
}

impl dbus::message::SignalArgs for OrgKdeStatusNotifierWatcherStatusNotifierItemUnregistered {
    const NAME: &'static str = "StatusNotifierItemUnregistered";
    const INTERFACE: &'static str = "org.kde.StatusNotifierWatcher";
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target = T>> OrgKdeStatusNotifierWatcher
    for blocking::Proxy<'a, C>
{
    fn get_registered_items(&self) -> Result<Vec<String>, dbus::Error> {
        self.method_call("org.kde.StatusNotifierWatcher", "GetRegisteredItems", ())
            .and_then(|r: (Vec<String>,)| Ok(r.0))
    }

    fn register_status_notifier_host(&self, service: &str) -> Result<(), dbus::Error> {
        self.method_call(
            "org.kde.StatusNotifierWatcher",
            "RegisterStatusNotifierHost",
            (service,),
        )
    }

    fn register_status_notifier_item(&self, service: &str) -> Result<(), dbus::Error> {
        self.method_call(
            "org.kde.StatusNotifierWatcher",
            "RegisterStatusNotifierItem",
            (service,),
        )
    }

    fn is_status_notifier_host_registered(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "org.kde.StatusNotifierWatcher",
            "IsStatusNotifierHostRegistered",
        )
    }

    fn protocol_version(&self) -> Result<i32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "org.kde.StatusNotifierWatcher",
            "ProtocolVersion",
        )
    }

    fn registered_status_notifier_items(&self) -> Result<Vec<String>, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "org.kde.StatusNotifierWatcher",
            "RegisteredStatusNotifierItems",
        )
    }
}
